name: publish to nuget
on:
  push:
    branches:
      - main # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 
      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: alirezanet/publish-nuget@v3.0.0
        with: 
          PROJECT_FILE_PATH: src/CommandLineArgsGenerator.csproj 
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
